---
title: "Chapter-4"
author: "Gavin McCorry"
date: "2024-03-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

# Positiv Integers
```{r}
deck <- read.csv("C:/Users/gwmcc/OneDrive/Documents/GitHub/Data-332/Chapter-3/cards.csv")

head(deck)
deck[1, 1]

# extracting more than one value
deck[1, c(1, 2, 3)]

# Saving to an R object
new <- deck[1, c(1, 2, 3)]
new

# Repetition
deck[c(1, 1), c(1, 2, 3)]

# Can subset a vector with a single index
vec <- c(6, 1, 3, 6, 10, 5)
vec[1:3]
```

# Negativee Numbers
```{r}
deck[-(2:52), 1:3]
```

# Zero
```{r}
deck[0, 0]
# Not verey helpful
```

# Blank Spaces
```{r}
# use to tell R to extract every value in a dimension
deck[1, ]
```

# Logical Values
```{r}
deck[1, c(TRUE, TRUE, FALSE)]

rows <- c(TRUE, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F ,F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F ,F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F)

deck[rows, ]
```

# Names
```{r}
deck[1, c("face", "suit", "value")]

deck[ , "value"]
```

# Deal A Card
```{r}
deal <- function(cards){
  cards[1, ]
}

deal(deck)
```
# Shuffling the Deck
```{r}
deck2 <- deck[1:52, ]
head(deck2)

deck3 <- deck[c(2, 1, 3:52), ]
head(deck3)

random <- sample(c(1:52), size =52)
random

deck4 <- deck[random, ]
head(deck4)
```

# Shuffle Function
```{r}
shuffle <- function(cards) {
  random <- sample(c(1:52), size = 52)
  cards[random,]
}

deal(deck)

deck2 <- shuffle(deck)
deal(deck2)
```

# Dollar Signs and Double Brackets
```{r}
deck$value

mean(deck$value)
median(deck$value)

lst <- list(numbers = c(1, 2), logical = TRUE, strings = c("a", "b", "c"))
lst

lst[1]

sum(lst$numbers)
sum(lst[[1]])

lst["numbers"]
lst[["numbres"]]
```

